# Generated by Django 2.2.24 on 2021-06-15 21:44

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_vimeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolvimeovideo',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, default=None, max_length=255),
        ),
    ]
