# Generated by Django 2.2.24 on 2021-07-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eol_vimeo', '0002_auto_20210615_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eolvimeovideo',
            unique_together={('edx_video_id', 'course_key')},
        ),
        migrations.AlterIndexTogether(
            name='eolvimeovideo',
            index_together={('edx_video_id', 'course_key')},
        ),
    ]
