# Generated by Django 2.2.24 on 2021-07-30 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_vimeo', '0003_auto_20210730_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolvimeovideo',
            name='edx_video_id',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid edx_video_id', message='edx_video_id has invalid characters', regex='^[a-zA-Z0-9\\-_]*$')]),
        ),
    ]
