# Generated by Django 2.2.24 on 2022-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_vimeo', '0005_auto_20210910_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolvimeovideo',
            name='url_picture',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
